### ISSUE TITLE
anyURI values containing pipes are not parseable by the org.hl7.fhir.core library

### ISSUE THREAD

**Issue by balhoff** [w3c/hcls-fhir-rdf#155]
**Turtle filename**
`allergyintolerance.profile.ttl`

That file and other profile files contain lines like this:

```turtle
fhir:valueSet [
           fhir:v "http://hl7.org/fhir/ValueSet/all-languages|5.0.0"^^xsd:anyURI ;
           fhir:link <http://hl7.org/fhir/ValueSet/all-languages|5.0.0>
         ]
```

The value "http://hl7.org/fhir/ValueSet/all-languages|5.0.0"^^xsd:anyURI is not parseable by the https://github.com/hapifhir/org.hl7.fhir.core library, which is used to generate the Turtle examples and can also read them back in. Running the test generator gives this error when trying to roundtrip:

```
org.hl7.fhir.exceptions.FHIRFormatError: Illegal URI http://hl7.org/fhir/ValueSet/all-languages|5.0.0
	at org.hl7.fhir.utilities.turtle.Turtle$TTLURL.setUri(Turtle.java:727)
	at org.hl7.fhir.utilities.turtle.Turtle.parseComplex(Turtle.java:1232)
	at org.hl7.fhir.utilities.turtle.Turtle.parseComplex(Turtle.java:1228)
	at org.hl7.fhir.utilities.turtle.Turtle.parseComplex(Turtle.java:1228)
	at org.hl7.fhir.utilities.turtle.Turtle.parseComplex(Turtle.java:1228)
	at org.hl7.fhir.utilities.turtle.Turtle.parseComplex(Turtle.java:1228)
	at org.hl7.fhir.utilities.turtle.Turtle.parse(Turtle.java:1175)
	at org.hl7.fhir.utilities.turtle.Turtle.parse(Turtle.java:1106)
	at org.hl7.fhir.r5.test.TurtleGeneratorTests.parseGeneratedTurtle(TurtleGeneratorTests.java:120)
	at org.hl7.fhir.r5.test.TurtleGeneratorTests.testInstanceGeneration(TurtleGeneratorTests.java:102)
	at org.hl7.fhir.r5.test.TurtleGeneratorTests.testPublishedExamples(TurtleGeneratorTests.java:87)
	<trimmed>
```

The error comes from this method (https://github.com/hapifhir/org.hl7.fhir.core/blob/7740b5d857013a905e99d1d82a530d82b58cdf29/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/turtle/Turtle.java#L725) which uses this IRI regex: https://github.com/hapifhir/org.hl7.fhir.core/blob/7740b5d857013a905e99d1d82a530d82b58cdf29/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/turtle/Turtle.java#L54

**Comment by balhoff** [comment]
Jena riot 5.0.0 gives these warnings:

```
riot --validate fhir-examples-out-orig/allergyintolerance.profile.ttl
13:49:21 WARN  riot            :: [line: 283, col: 66] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/all-languages[|]...>
13:49:21 WARN  riot            :: [line: 283, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/all-languages|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 520, col: 80] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergyintolerance-clinical[|]...>
13:49:21 WARN  riot            :: [line: 520, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergyintolerance-clinical|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 569, col: 84] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergyintolerance-verification[|]...>
13:49:21 WARN  riot            :: [line: 569, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergyintolerance-verification|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 674, col: 81] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergy-intolerance-category[|]...>
13:49:21 WARN  riot            :: [line: 674, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergy-intolerance-category|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 726, col: 84] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality[|]...>
13:49:21 WARN  riot            :: [line: 726, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 1624, col: 76] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/reaction-event-severity[|]...>
13:49:21 WARN  riot            :: [line: 1624, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/reaction-event-severity|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 1779, col: 80] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergyintolerance-clinical[|]...>
13:49:21 WARN  riot            :: [line: 1779, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergyintolerance-clinical|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 1813, col: 84] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergyintolerance-verification[|]...>
13:49:21 WARN  riot            :: [line: 1813, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergyintolerance-verification|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 1888, col: 81] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergy-intolerance-category[|]...>
13:49:21 WARN  riot            :: [line: 1888, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergy-intolerance-category|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 1925, col: 84] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality[|]...>
13:49:21 WARN  riot            :: [line: 1925, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
13:49:21 WARN  riot            :: [line: 2357, col: 76] Illegal character in IRI (codepoint 0x7C, '|'): <http://hl7.org/fhir/ValueSet/reaction-event-severity[|]...>
13:49:21 WARN  riot            :: [line: 2357, col: 22] Bad IRI: <http://hl7.org/fhir/ValueSet/reaction-event-severity|5.0.0> Code: 4/UNWISE_CHARACTER in PATH: The character matches no grammar rules of URIs/IRIs.
```

However, it is not complaining about the `xsd:anyURI` literals, but about the `fhir:link` IRIs that are also output, e.g. the second value here:

```turtle
fhir:valueSet [
  fhir:v "http://hl7.org/fhir/ValueSet/all-languages|5.0.0"^^xsd:anyURI ;
  fhir:link <http://hl7.org/fhir/ValueSet/all-languages|5.0.0>
] ;
```

**Comment by tmprd** [comment]
More background here: https://github.com/w3c/hcls-fhir-rdf/issues/120#issuecomment-1849044884
XSD 1.0 doesn't allow pipes, at least not without a URI encoding. But XSD 1.1 apparently allows anything, including pipes and spaces.

**Comment by dbooth-boston** [comment]
> However, it is not complaining about the `xsd:anyURI` literals, but about the `fhir:link` IRIs that are also output, e.g. the second value here:
> 
> fhir:valueSet [
>   fhir:v "http://hl7.org/fhir/ValueSet/all-languages|5.0.0"^^xsd:anyURI ;
>   fhir:link <http://hl7.org/fhir/ValueSet/all-languages|5.0.0>
> ] ;

@balhoff  , I think that fhir:link URI should have been converted to use a query string like `<http://hl7.org/fhir/ValueSet/all-languages|5.0.0>`  instead of a pipe symbol, as shown in the [example 4B in issue 120](https://github.com/w3c/hcls-fhir-rdf/issues/120#issue-1760478116).

**Comment by dbooth-boston** [comment]
Closing, as resolved by https://github.com/w3c-cg/hcls-fhir-rdf/issues/191
