### ISSUE TITLE
Import FHIR Ontology on Protege

### ISSUE THREAD

**Issue by Milena1530** [w3c/hcls-fhir-rdf#90]
I'm looking to import the FHIR Ontology on Protege. I'm struggling to find out which is the right sequence of files to import .

**Comment by ericprud** [comment]
Are you trying to load the [BLENDINGFHIRandRDF](https://github.com/BD2KOnFHIR/BLENDINGFHIRandRDF) files?

**Comment by Milena1530** [comment]
I've replaced the content of the catalog-v001.xml with the content of catalog-remote.xml. Then I've tried to import the wrapper.owl in Protege 5.5 through Direct Import --> Import an ontology contained in a local file, but it gave me this errore:

  ERROR  11:36:41  An error occurred whilst extracting the Ontology Id from the imported ontology: {}
java.lang.NullPointerException: null
	at org.protege.editor.owl.model.repository.MasterOntologyIDExtractor.getOntologyId(MasterOntologyIDExtractor.java:27) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.checkImport(AnticipateOntologyIdPage.java:109) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.lambda$new$0(AnticipateOntologyIdPage.java:44) [protege-editor-owl.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
   INFO  11:36:45  -------------------- Importing ontology and imports closure --------------------

**Comment by ericprud** [comment]
@hsolbrig, any thoughts?

**Comment by hsolbrig** [comment]
Been a while since I've taken this out for a test drive -- will give it a look.  OK if we transfer this issue to the Blending page?

**Comment by Milena1530** [comment]
That sounds good, thank you very much

**Comment by hsolbrig** [comment]
https://github.com/BD2KOnFHIR/BLENDINGFHIRandRDF/issues/6

**Comment by ericprud** [comment]
closing, noting that the issue has been forwarded to BD2KOnFHIR/BLENDINGFHIRandRDF#6
